/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    members: Member;
    memberships: Membership;
    events: Event;
    news: News;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'staff' | 'member') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  status?: ('SUBMITTED' | 'PENDING_PAYMENT' | 'PAYMENT_SUBMITTED' | 'ACTIVE' | 'REJECTED') | null;
  membershipType: 'associate' | 'allied' | 'premier';
  companyName: string;
  companyType: string;
  companyCategory: string;
  typeOfCompany: string;
  city: string;
  state: string;
  address: string;
  pincode: string;
  website?: string | null;
  gstin: string;
  tanNo?: string | null;
  panNo: string;
  yearOfEstablishment: string;
  legalEntity: string;
  globalHeadquarters?: string | null;
  socialMediaHandle?: string | null;
  contactDesignation: string;
  contactTitle: string;
  contactFirstName: string;
  contactLastName: string;
  contactMobile: string;
  contactEmail: string;
  headDesignation: string;
  headTitle: string;
  headFirstName: string;
  headLastName: string;
  headMobile: string;
  headEmail: string;
  companyProfile: string;
  areasOfInterest?: ('manufacturing' | 'it-services' | 'consultancy')[] | null;
  totalEmployees?: string | null;
  employeeYear?: string | null;
  totalRevenue?: string | null;
  revenueYear?: string | null;
  businessType?: string | null;
  turnover?: string | null;
  registrationNumber?: string | null;
  gstNumber?: string | null;
  udyamNumber?: string | null;
  factoryRegistration?: string | null;
  powerConnection?: string | null;
  pollutionClearance?: string | null;
  description?: string | null;
  createdBy?: (number | null) | User;
  /**
   * Membership fee applicable for this application
   */
  feeAmount?: number | null;
  /**
   * Payment reference ID from PayU
   */
  paymentReferenceId?: string | null;
  paymentVerifiedAt?: string | null;
  activatedAt?: string | null;
  rejectionReason?: string | null;
  rejectedAt?: string | null;
  /**
   * Whether the membership certificate has been sent to the member
   */
  certificateSent?: boolean | null;
  /**
   * Date when the membership certificate was sent
   */
  certificateSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the 3 membership types and their pricing. Only Associate, Allied, and Premier memberships are allowed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  /**
   * Unique identifier for the membership type (only 3 types allowed)
   */
  type: 'associate' | 'allied' | 'premier';
  /**
   * Membership fee in INR
   */
  price: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Title of the event
   */
  title: string;
  /**
   * URL slug for the event (leave empty to auto-generate from title)
   */
  slug: string;
  category: 'conference' | 'workshop' | 'awards' | 'seminar' | 'training' | 'networking' | 'other';
  status: 'unpublished' | 'published' | 'cancelled' | 'completed';
  /**
   * Featured image for the event
   */
  featuredImage: number | Media;
  /**
   * Short description of the event (max 300 characters)
   */
  excerpt: string;
  /**
   * Full description of the event
   */
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date of the event
   */
  eventDate: string;
  /**
   * Time of the event (e.g., 9:00 AM - 6:00 PM)
   */
  eventTime: string;
  /**
   * Location of the event (e.g., Lucknow, Uttar Pradesh)
   */
  location: string;
  /**
   * Specific venue details
   */
  venue?: string | null;
  /**
   * Event agenda or schedule
   */
  agenda?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Feature this event on the homepage
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * Title of the news article
   */
  title: string;
  /**
   * URL slug for the news article (leave empty to auto-generate from title)
   */
  slug: string;
  category:
    | 'events'
    | 'policy'
    | 'training'
    | 'awards'
    | 'industry-news'
    | 'government-updates'
    | 'partnership'
    | 'press-release'
    | 'other';
  status: 'draft' | 'published' | 'archived';
  /**
   * Featured image for the news article
   */
  featuredImage: number | Media;
  /**
   * Short description of the news (max 300 characters)
   */
  excerpt: string;
  /**
   * Full content of the news article
   */
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Publication date of the news
   */
  publishedDate: string;
  /**
   * Author of the news article
   */
  author?: string | null;
  /**
   * Author's designation or title
   */
  authorDesignation?: string | null;
  /**
   * Tags for better categorization and search
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Related events (if any)
   */
  relatedEvents?: (number | Event)[] | null;
  /**
   * External URL for more information (optional)
   */
  externalUrl?: string | null;
  /**
   * Downloadable files related to this news (PDFs, documents, etc.)
   */
  downloadableFiles?:
    | {
        title: string;
        file: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Feature this news on the homepage
   */
  isFeatured?: boolean | null;
  /**
   * Mark as breaking news
   */
  isBreaking?: boolean | null;
  /**
   * Priority for homepage display order
   */
  priority?: ('high' | 'medium' | 'low') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  status?: T;
  membershipType?: T;
  companyName?: T;
  companyType?: T;
  companyCategory?: T;
  typeOfCompany?: T;
  city?: T;
  state?: T;
  address?: T;
  pincode?: T;
  website?: T;
  gstin?: T;
  tanNo?: T;
  panNo?: T;
  yearOfEstablishment?: T;
  legalEntity?: T;
  globalHeadquarters?: T;
  socialMediaHandle?: T;
  contactDesignation?: T;
  contactTitle?: T;
  contactFirstName?: T;
  contactLastName?: T;
  contactMobile?: T;
  contactEmail?: T;
  headDesignation?: T;
  headTitle?: T;
  headFirstName?: T;
  headLastName?: T;
  headMobile?: T;
  headEmail?: T;
  companyProfile?: T;
  areasOfInterest?: T;
  totalEmployees?: T;
  employeeYear?: T;
  totalRevenue?: T;
  revenueYear?: T;
  businessType?: T;
  turnover?: T;
  registrationNumber?: T;
  gstNumber?: T;
  udyamNumber?: T;
  factoryRegistration?: T;
  powerConnection?: T;
  pollutionClearance?: T;
  description?: T;
  createdBy?: T;
  feeAmount?: T;
  paymentReferenceId?: T;
  paymentVerifiedAt?: T;
  activatedAt?: T;
  rejectionReason?: T;
  rejectedAt?: T;
  certificateSent?: T;
  certificateSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  type?: T;
  price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  status?: T;
  featuredImage?: T;
  excerpt?: T;
  description?: T;
  eventDate?: T;
  eventTime?: T;
  location?: T;
  venue?: T;
  agenda?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  status?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  publishedDate?: T;
  author?: T;
  authorDesignation?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedEvents?: T;
  externalUrl?: T;
  downloadableFiles?:
    | T
    | {
        title?: T;
        file?: T;
        description?: T;
        id?: T;
      };
  isFeatured?: T;
  isBreaking?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}